name: Merge Dev to QA

on:
 push:
    branches:
      - dev

jobs:
 merge-to-qa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Push to QA
        run: |
          git push origin dev:qa

      - name: Wait for GitHub to process the push
        run: sleep 10

      - name: Create Pull Request
        run: |
          hub pull-request -b qa -h dev --no-edit -m "[Automated] Merge dev to qa" -m "Automated Pull Request to merge changes from dev to qa" -r your-reviewer-username -a your-assignee-username || true
